/* eslint-disable quotes */
// for login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

// get profile data
export const GET_PROFILE_DATA_REQUEST = "GET_PROFILE_DATA_REQUEST";
export const GET_PROFILE_DATA_REQUEST_SUCCESS = "GET_PROFILE_DATA_REQUEST_SUCCESS";
export const GET_PROFILE_DATA_REQUEST_FAILURE = "GET_PROFILE_DATA_REQUEST_FAILURE";

// get all deals
export const GET_ALL_DEALS_REQUEST = "GET_ALL_DEALS_REQUEST";
export const GET_ALL_DEALS_REQUEST_SUCCESS = "GET_ALL_DEALS_REQUEST_SUCCESS";
export const GET_ALL_DEALS_REQUEST_FAILURE = "GET_ALL_DEALS_REQUEST_FAILURE";

// get single deal
export const GET_DEAL_REQUEST = "GET_DEAL_REQUEST";
export const GET_DEAL_REQUEST_SUCCESS = "GET_DEAL_REQUEST_SUCCESS";
export const GET_DEAL_REQUEST_FAILURE = "GET_DEAL_REQUEST_FAILURE";

// get all payments
export const GET_ALL_PAYMENTS_REQUEST = "GET_ALL_PAYMENTS_REQUEST";
export const GET_ALL_PAYMENTS_REQUEST_SUCCESS = "GET_ALL_PAYMENTS_REQUEST_SUCCESS";
export const GET_ALL_PAYMENTS_REQUEST_FAILURE = "GET_ALL_PAYMENTS_REQUEST_FAILURE";

// get single payment
export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST"
export const GET_PAYMENT_REQUEST_SUCCESS = "GET_PAYMENT_REQUEST_SUCCESS"
export const GET_PAYMENT_REQUEST_FAILURE = "GET_PAYMENT_REQUEST_FAILURE"

// scan qr code
export const SCAN_QR_CODE_REQUEST = "SCAN_QR_CODE_REQUEST";
export const SCAN_QR_CODE_REQUEST_SUCCESS = "SCAN_QR_CODE_REQUEST_SUCCESS";
export const SCAN_QR_CODE_REQUEST_FAILURE = "SCAN_QR_CODE_REQUEST_FAILURE";

// get packages all
export const GET_ALL_PACKAGES_REQUEST = "GET_ALL_PACKAGES_REQUEST";
export const GET_ALL_PACKAGES_REQUEST_SUCCESS = "GET_ALL_PACKAGES_REQUEST_SUCCESS";
export const GET_ALL_PACKAGES_REQUEST_FAILURE = "GET_ALL_PACKAGES_REQUEST_FAILURE";

// get package single
export const GET_PACKAGE_REQUEST = "GET_PACKAGE_REQUEST";
export const GET_PACKAGE_REQUEST_SUCCESS = "GET_PACKAGE_REQUEST_SUCCESS";
export const GET_PACKAGE_REQUEST_FAILURE = "GET_PACKAGE_REQUEST_FAILURE";

// redeem deals
export const REDEEM_DEAL_REQUEST = "REDEEM_DEAL_REQUEST"
export const REDEEM_DEAL_REQUEST_SUCCESS = "REDEEM_DEAL_REQUEST_SUCCESS"
export const REDEEM_DEAL_REQUEST_FAILURE = "REDEEM_DEAL_REQUEST_FAILURE"

// show coupons
export const SHOW_COUPON_REQUEST = "SHOW_COUPON_REQUEST"
export const SHOW_COUPON_REQUEST_SUCCESS = "SHOW_COUPON_REQUEST_SUCCESS"
export const SHOW_COUPON_REQUEST_FAILURE = "SHOW_COUPON_REQUEST_FAILURE"